<!DOCTYPE html>
<html>

<head>
    <title>Visualizza libro</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootsrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Font awesome -->
    <script src="https://kit.fontawesome.com/a0289c987d.js" crossorigin="anonymous"></script>
    <!-- Stylesheet -->
    <link rel="stylesheet" href="CSS/style.css">
</head>

<body>
    <div class="container-fluid container-fullpage">
        <div class="wrap-libro">
            <div class="wrap-left">
                <div class="wrap-copertina">
                    <?php
                    echo "<img src=" . $data["copertina"] . ">";
                    ?>
                </div>
                <?php
                    if(isset($_SESSION["accountLevel"]) && $_SESSION["accountLevel"]==2){
                        echo "<button>Elimina</button>";
                    }
                ?>
            </div>
            <div class="wrap-right">
                <h1 id="titolo"><?php echo $data["titolo"]; ?></h1>
                <p id="autori">Autori:</p>

                <p id="CE">Casa editrice:</p>

            </div>
        </div>
    </div>
</body>

</html>