<!DOCTYPE html>
<html lang="it">

<head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootsrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Font awesome -->
    <script src="https://kit.fontawesome.com/a0289c987d.js" crossorigin="anonymous"></script>
    <!-- Stylesheet -->
    <link rel="stylesheet" href="CSS/style.css">
    <script>

    </script>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div id="sidebar" class="sidebar">
                <div class="sidebarHeader">
                    <form id="searchbar">
                        <i class="fa fa-search" aria-hidden="true"></i>
                        <input type="search" id="search" placeholder="Cerca un libro">
                    </form>
                </div>
                <hr class="sidebarDivider">
                <div class="sidebarContent">
                    <div class="vr">
                        <a href="#">Services</a>
                        <a href="#">Clients</a>
                        <a href="#">Contact</a>
                    </div>
                </div>
                <div class="sidebarFooter">
                    <div id="profilo">
                        <div class="row">
                            <div class="col-2 align-middle">
                                <i class="fa fa-user focus-input"></i>
                            </div>
                            <div class="col">
                                <?php
                                if (!isset($_SESSION["logged"])) {
                                    echo "<a href='login'>Effettua il login</a><br>";
                                } else {
                                    echo "Benvenuto " . $_SESSION["idAccount"] . "</br>";
                                    echo "<a href='logout'>Effettua il logout</a><br>";
                                }
                                ?>
                            </div>
                        </div>


                    </div>
                </div>
            </div>

            <!-- Main body-->
            <div class="col">
                <main role="main">
                    <div class="row">
                        <div class="column">
                            <div class="header">
                                <h1 class="titolo">Leggere di scienza</h1>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="column">

                        </div>
                    </div>
                    <h1 class="text-coffee">Benvenuti nel sito</h1>
                    <?php
                    if (!isset($_SESSION["logged"])) {
                        echo "<a href='login'>Effettua il login</a><br>";
                    } else {
                        echo "Benvenuto " . $_SESSION["idAccount"] . "</br>";
                        echo "<a href='logout'>Effettua il logout</a><br>";
                    }
                    ?>

                    <a href="CCC"> Ciao </a>
                    <p>Libri:</p>

                    <form method="post" action="visualizzaLibro">
                        <?php
                        foreach ($data["books"] as $book) {

                            $idLibro = $book["idLibro"];
                            $titoloLibro = $book["titolo"];

                            echo "<input type='hidden' name='idLibro' value='$idLibro' />";
                            echo "<a onclick='this.parentNode.submit();'>$titoloLibro</a><br>";
                        }
                        ?>
                    </form>
                    <?= json_encode($data); ?>
                </main>
            </div>
        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <h1>Ciao</h1>


    <!-- Footer -->



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>