<!DOCTYPE html>
<html lang="it">

<head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
    <!-- Header -->
    <nav class="navbar navbar-expand-sm fixed-top bg-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="home">Libreria JFKennedy</a>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse">
                    <div class="row">
                        <div class="col-md-8">
                            <ul class="navbar-nav mr-auto col-sm-auto">
                                <li class="nav-item active">
                                    <a class="nav-link" href="home">Home <span class="sr-only">(current)</span></a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-6 col-md-4">
                            <form class="form-inline mt-2 mt-md-0 col-md-5">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                            </form>
                        </div>
                    </div>
            </div>
        </div>
    </nav>

    <div class="pt-5"></div>
    <div class="pt-3"></div>
    <!-- Main body -->
    <main role="main" class="container">
        <h1>Benvenuti nel sito</h1>
        <?php 
            if(!isset($_SESSION["logged"])){
                echo "<a href='login'>Effettua il login</a><br>";
            }else{
                echo "Benvenuto " . $_SESSION["idAccount"] . "</br>";
                echo "<a href='logout'>Effettua il logout</a><br>";
                echo "<a href='inserisciLibro'>Inserisci un nuovo libro</a><br>";
            }
        ?>
        <p>Libri:</p>

        <form method="post" action="visualizzaLibro">
            <?php
            foreach($data["books"] as $book){

                $idLibro = $book["idLibro"];
                $titoloLibro = $book["titolo"];

                echo "<input type='hidden' name='idLibro' value='$idLibro' />" ;
                echo "<a onclick='this.parentNode.submit();'>$titoloLibro</a><br>";
            }
        ?>
        </form>
    </main>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br><h1>Ciao</h1>


    <!-- Footer -->



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>