<!DOCTYPE html>
<html lang="it">

<head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="CSS/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/a0289c987d.js" crossorigin="anonymous"></script>
    <script>
        
    </script>
</head>

<body class="bg-almond">
    <!-- Side navigation -->
    <div id="sideNav" class="sidenav">
        <div class="searchBar">
                <form class="container inputs col-md-10 p-0">
                    <i class="fa fa-search"></i>
                    <input type="text" class="search" placeholder="Cerca un libro">
                </form>
        </div>
        <a href="#">Services</a>
        <a href="#">Clients</a>
        <a href="#">Contact</a>
    </div>

    <!-- Main body -->
    <main role="main">
        <h1 class="text-coffee">Benvenuti nel sito</h1>
        <?php 
            if(!isset($_SESSION["logged"])){
                echo "<a href='login'>Effettua il login</a><br>";
            }else{
                echo "Benvenuto " . $_SESSION["idAccount"] . "</br>";
                echo "<a href='logout'>Effettua il logout</a><br>";
                echo "<a href='inserisciLibro'>Inserisci un nuovo libro</a><br>";
            }
        ?>
        <p>Libri:</p>

        <form method="post" action="visualizzaLibro">
            <?php
            foreach($data["books"] as $book){

                $idLibro = $book["idLibro"];
                $titoloLibro = $book["titolo"];

                echo "<input type='hidden' name='idLibro' value='$idLibro' />" ;
                echo "<a onclick='this.parentNode.submit();'>$titoloLibro</a><br>";
            }
        ?>
        </form>
        <?= json_encode($data);?>
    </main>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br><h1>Ciao</h1>


    <!-- Footer -->



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>