<!DOCTYPE html>
<html>

<head>
    <title>Inserimento di un nuovo libro</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="data" content='<?= json_encode($data); ?>'>
    <!-- Bootsrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Font awesome -->
    <script src="https://kit.fontawesome.com/a0289c987d.js" crossorigin="anonymous"></script>

    <!-- Stylesheet -->
    <link rel="stylesheet" href="CSS/style.css">
    
</head>

<body>
    <div class="container-fluid">
        <div class="insert">
            <!-- HEADER -->
            <div class="insert-header">
                <div class="insert-header-home">
                    <a href="home"><img src="img/logo_JFK.png"></a>
                </div>
                <div class="insert-header-profile">

                    <?php
                    echo "<h3>" . $_SESSION["accountInfo"]["nome"] . " " . $_SESSION["accountInfo"]["cognome"] . "</h3>";
                    ?>

                    <a href="home"><i class="fa fa-user-circle" style="font-size:48px" aria-hidden="true"></i></a>
                </div>
            </div>
            <!-- CONTENT -->
            <div class="insert-content">
                <!-- FORM  -->
                <div class="insert-content-fields">
                    <form method="post" action="inserisciLibro" enctype="multipart/form-data">
                        <input type="hidden" name="insertBook" value="true">


                        <!-- Titolo -->
                        <div class="insert-content-fields-row">
                            <label for="titolo">Titolo:</label>
                            <input type="text" name="titolo" required>
                        </div>

                        <!-- ISBN -->
                        <div class="insert-content-fields-row">
                            <label for="ISBN">ISBN:</label>
                            <input type="text" name="ISBN">
                        </div>

                        <!-- Inserimento copertina-->
                        <div class="insert-content-fields-row">
                            <label for="copertina">Inserisci un'immagine di copertina:</label>
                            <div class="insert-image">
                                <label class="custom-file-upload" for="file-upload"><i
                                        class="fa-solid fa-camera"></i></label>
                            </div>
                            <input type="file" id="file-upload" name="copertina" accept="image/png, image/jpeg" />
                        </div>

                        <!-- Casa editrice -->
                        <div class="insert-content-fields-row">
                            <label for="idCasaEditrice">Casa Editrice: </label>
                            <div class="autocomplete">
                                <input class="input-text" type="text" id="ce-input"
                                    placeholder="Inserisci una casa editrice..." />
                                <ul class="ce-list"></ul>
                            </div>
                        </div>

                        <!-- Tipologia del libro-->
                        <div class="insert-content-fields-row">
                            <label for="idTipologia">Tipologia: </label>
                            <div class="autocomplete">
                                <input class="input-text" type="text" id="tp-input"
                                    placeholder="Inserisci una casa editrice..." />
                                <ul class="tp-list"></ul>
                            </div>
                        </div>

                        <!-- Data di pubblicazione -->
                        <div class="insert-content-fields-row">
                            <label for="dataPubblicazione">Data di pubblicazione: </label>
                            <input type="date" name="dataPubblicazione">
                        </div>

                        <!-- Generi -->

                        <!-- Trama -->
                        <div class="insert-content-fields-row">
                            <label for="trama">Trama: </label>
                            <input type="text" name="Trama">
                        </div>

                        <!-- Disponibilità in biblioteca -->
                        <div class="insert-content-fields-row">
                            <label for="disponibilita">Disponibile in biblioteca: </label>
                            <input type="checkbox" name="disponibilita">
                        </div>

                        <!-- Tasto  Submit -->
                        <div class="insert-content-fields-row">
                            <label></label>
                            <input type="submit" value="Inserisci">
                        </div>
                    </form>
                    <script src="JS/searchAutocomplete.js"></script>
                </div>
            </div>

            <!-- Autori -->



            <!-- Argomenti -->

            <!-- Parole chiave -->
        </div>
    </div>
    <!-- FOOTER -->
    <div class="insert-footer">

    </div>
    </div>
    </div>




</body>

</html>