<!DOCTYPE html>
<html lang="it">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Bootsrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Font awesome -->
    <script src="https://kit.fontawesome.com/a0289c987d.js" crossorigin="anonymous"></script>
    <!-- Stylesheet -->
    <link rel="stylesheet" href="CSS/style.css">
<!--===============================================================================================-->
</head>
<body>
		<div class="container-login">
			<div class="wrap-login">
				<form class="login-form validate-form">
					<span class="login-form-logo">
						<i class="fa fa-book"></i>
					</span>

					<span class="login-form-title p-b-34 p-t-27">
						Effettua l'accesso all'account
					</span>
					<div class="wrap-input validate-input" data-validate = "Enter username">
						<div class="row">
							<div class="col-2 align-middle">
								<i class="fa fa-user focus-input"></i>
							</div>
							<div class="col">
								<input class="input" type="text" name="username" placeholder="Username">
							</div>
						</div>
					</div>

					<div class="wrap-input validate-input" data-validate="Enter password">
						<input class="input" type="password" name="pass" placeholder="Password">
						<span class="focus-input"></span>
					</div>

					<div class="contact-form-checkbox">
						<input class="input-checkbox" id="ckb1" type="checkbox" name="remember-me">
						<label class="label-checkbox" for="ckb1">
							Ricordami
						</label>
					</div>

					<div class="container-login-form-btn">
						<button class="login-form-btn">
							Accedi
						</button>
					</div>

					<div class="text-center p-t-90">
						<a class="txt1" href="#">
							Password dimenticata?
						</a>
					</div>
				</form>
			</div>
	</div>
	

	<div id="dropDownSelect1"></div>

</body>
</html>