<!DOCTYPE html>
<html lang="it">

<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Bootsrap -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<!-- Font awesome -->
	<script src="https://kit.fontawesome.com/a0289c987d.js" crossorigin="anonymous"></script>
	<!-- Stylesheet -->
	<link rel="stylesheet" href="CSS/style.css">
</head>

<body>
	<div class="container-fullpage"> <!--style="background-image: url('img/background.jpg');"-->
		<div class="wrap-login">
			<form id="loginForm" class="login-form validate-form" method="post" action="login">
				<input type="hidden" name="login" value="true">
				<span class="login-form-logo">
					<i class="fa fa-book"></i>
				</span>

				<span class="login-form-title">
					Effettua l'accesso all'account
				</span>

				<!-- Username -->
				<div class="row wrap-input validate-input">
					<div class="col-2 form-icon">
						<i class="fa fa-user focus-input"></i>
					</div>
					<div class="col form-input" data-validate="Inserisci un nome utente!">
						<input class="input" type="text" name="username" placeholder="Username">
					</div>
				</div>

				<!-- Password -->
				<div class="row wrap-input validate-input">
					<div class="col-2 form-icon">
						<i class="fa fa-lock"></i>
					</div>
					<div class="col form-input" data-validate="Inserisci una password!">
						<input class="input" type="password" name="password" placeholder="Password">
					</div>
				</div>

				<!-- Submit -->
				<div class="container-login-form-btn">
					<button class="login-form-btn">
						Accedi
					</button>
				</div>


				<!-- TODO -->
				<div class="text-center p-t-90">
					<a class="txt1" href="#">
						Non hai un account?
					</a>
				</div>
			</form>
		</div>
	</div>
	<!-- jQuery -->
	<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
	<!-- Scripts -->
	<script src="JS/login.js"></script>
</body>

</html>