<!DOCTYPE html>
<html>

<head>
    <title>Login</title>
    <style>
        #container {
            display: flex;      /* establish flex container */
            flex-direction: column;     /* stack flex items vertically */
            justify-content: center;        /* center items vertically, in this case */
            align-items: center;        /* center items horizontally, in this case */
            height: 100%;
            border: 1px solid black;
        }

        .box {
            width: 300px;
            margin: 5px;
            text-align: center;
        }
    </style>
</head>

<body>
    <div id="container">
        <div class="box">
            <form method="post" action="login">
                <input type="hidden" name="login" value="true">
                <label>username: </label>
                <input type="text" name="username"><br>
                <label>Password: </label>
                <input type="password" name="password"><br>
                <input type="submit" value="Accedi">
            </form>
            <a href="register">Non hai un account? Registrati ora</a>
            <br>
            <a href="home">Torna indietro</a>
            <?= (isset($data["failed"])) ? "Login failed" : ''; ?>
        </div>
    </div>
</body>

</html>